export const TICKET_MIN_WIDTH = 537;
export const CUSTOMIZER_MIN_WIDTH = 215;
export const GAP_BETWEEN_CUSTOMIZER_AND_TICKET = 15;
export const CUSTOMIZER_WITH_TICKET_MIN_WIDTH =
    TICKET_MIN_WIDTH + GAP_BETWEEN_CUSTOMIZER_AND_TICKET + CUSTOMIZER_MIN_WIDTH;
